In [1]:
from fpdf import FPDF
import pandas as pd
import math

In [2]:
df = pd.read_excel('D9 BOARDGAME FACTORY PACKING LIST_FINAL by Nancy 062321.xlsx', sheet_name='data-061821', header=0)
df

,CONFIG,Carton Type,ORDER #,Carton of Total,SKU-D9-56EXPANSION,SKU-D9-ALLY-PACK,SKU-D9-BASE-GAME,SKU-D9-EXTRA-MINIS,SKU-D9-PUDDI-CAN,SKU-D9-SLEEVES,SKU-D9-TOKENS,Total items in Carton,WarehoUS - Transgroupe,Shipping Country
0,16,2,1676261,1 of 4,1.0,1.0,1.0,NaN,1.0,1.0,1.0,6,EU - Neelevat,Austria
1,16,2,1676261,2 of 4,1.0,1.0,1.0,NaN,1.0,1.0,1.0,6,EU - Neelevat,Austria
2,16,2,1676261,3 of 4,1.0,1.0,1.0,NaN,1.0,1.0,1.0,6,EU - Neelevat,Austria
3,16,2,1676261,4 of 4,1.0,1.0,1.0,NaN,1.0,1.0,1.0,6,EU - Neelevat,Austria
4,16,2,1676223,1 of 4,1.0,1.0,1.0,NaN,1.0,1.0,1.0,6,EU - Neelevat,Germany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,45,2,1676590,1 of 1,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1,US - Transgroup,United States
894,45,2,1676591,1 of 1,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1,US - Transgroup,United States
895,45,2,1751954,1 of 1,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1,US - Transgroup,United States
896,45,2,1676511,1 of 1,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1,US - Transgroup,United States
897,46,5,1676497,1 of 1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1,US - Transgroup,United States

In [7]:
df["WarehoUS - Transgroupe"].unique()

array(['EU - Neelevat', 'NZ - Weta', 'US - Transgroup'], dtype=object)

In [8]:
cols = df.columns
cols

Index(['CONFIG', 'Carton Type', 'ORDER #', 'Carton of Total',
       'SKU-D9-56EXPANSION', 'SKU-D9-ALLY-PACK', 'SKU-D9-BASE-GAME',
       'SKU-D9-EXTRA-MINIS', 'SKU-D9-PUDDI-CAN', 'SKU-D9-SLEEVES',
       'SKU-D9-TOKENS', 'Total items in Carton', 'WarehoUS - Transgroupe',
       'Shipping Country'],
      dtype='object')

In [9]:
cols = ['Shipping Country','WarehoUS - Transgroupe','CONFIG', 'Carton Type', 'ORDER #', 'Carton of Total',
       'SKU-D9-56EXPANSION', 'SKU-D9-ALLY-PACK', 'SKU-D9-BASE-GAME',
       'SKU-D9-EXTRA-MINIS', 'SKU-D9-PUDDI-CAN', 'SKU-D9-SLEEVES',
       'SKU-D9-TOKENS', 'Total items in Carton']

In [10]:
def create_label(row, cols):
    pdf = FPDF(orientation='p', unit='mm', format=(160, 180))
    pdf.add_page()
    pdf.set_font("Arial", size=14)
    
    for col in cols:
        if col.startswith("SKU") and math.isnan(row[col]):
            continue
        top = pdf.y
        offset = pdf.x + 80
        pdf.multi_cell(80, 10, col, 0, 0)
        pdf.y = top
        pdf.x = offset
        if col.startswith("SKU"): 
            pdf.multi_cell(100, 10, str(int(row[col])))
        else:
            pdf.multi_cell(100, 10, str(row[col]))
    country_code = row["WarehoUS - Transgroupe"][:2]
    filename = f"./labels/{country_code}-{row['CONFIG']}-{row['ORDER #']}-{row['Carton of Total']}.pdf"
    pdf.output(filename, "F")

In [11]:
for index, row in df.iterrows():
    create_label(row, cols)